### ISSUE TITLE
Some question about reporter.

### ISSUE THREAD

**Issue by Crossady** [ZjuDataStructure/Projects#2]
### chapter 2: 
In the first line, 

> "our algorithms is..."

 "is" may be "are".

### chapter 2.2.1:
 in the last,

>  "and n>=0"

 may be redundant. also in the first line in 2.2.2

### chapter 4:  
In the third line,

>  "we make comparison the result..." 

may be a syntax mistake.
            In the last sentence of the first paragraph,

>  "in order to making"

, should be "in order to make"

### chapter 4.2.1 : 
the first sentence 

> "be calculate" 

may be "be calculated"
                in the second sentence 

> "due to..."

, I can't understand the formula, maybe there is a mistake?

### chapter 4.3.1 :
 in the formula, I can't understand K's meaning.  

### chapter 4.4: 
a lot of 's's are lost.(my fault orz)

### **In the requirements, space complexity is required in chapter 4.**

**Comment by zurl** [comment]
@dfz chapter4.4？
