### ISSUE TITLE
Some other questions about Report

### ISSUE THREAD

**Issue by tanquer** [ZjuDataStructure/Projects#3]
## Contents

> Pesudo Code...

'Pesudo' should be 'Pseudo'.

### 1.1.1

> takes some value, or set of values

I think it should be 'takes some value**s**, or set of values' or 'takes a value, or set of values'.

> An algorithm is thus a sequence of computational steps that transform the input into the output.

Maybe it can paraphrase to 'Thus an algorithm is a a set of rules that precisely defines a sequence of operations (which transform the input into the output).'

### 1.1.2

> computational time

It should be 'computing time'

> in terms of performance measure

I don't know what does it mean, but it is very weird. Maybe it should be 'performance measurement'.

### 1.1.3

> DEFINITION: T(n) = O(f(n)) if there are constants c and n0 such that T(n) >= cf(n) when n <= n0.
DEFINITION: T(n) = Θ(g(n)) if there are constants c and n0 such that T(n) <= cg(n) when n >= n0.
DEFINITION: T(n) = Ω(h(n)) if and only if T(n) = O(h(n)) and T(n) = Θ(h(n)).
DEFINITION: T(n) = o(p(n)) if T(n) = O(p(n)) and T(n) != Ω(p(n)).

The symbols are defined totally incorrect. It should be :

DEFINITION: T(n) = O(f(n)) if there are constants c and n0 such that T(n) <= cf(n) when n >= n0.
DEFINITION: T(n) = Ω(g(n)) if there are constants c and n0 such that T(n) >= cg(n) when n >= n0.
DEFINITION: T(n) = Θ(h(n)) if and only if T(n) = O(h(n)) and T(n) = Θ(h(n)).
DEFINITION: T(n) = o(p(n)) if T(n) = O(p(n)) and T(n) != Θ(p(n)).

## 2

Every 'pesudo' should be 'pseudo'.

###2.2.1 & 2.2.2

> Our implementation restrict...

'restrict' should be 'restricts'.

## 4

> in order to making it be accurate.

I think it can change to 'in order to make it more accurate' or 'in order to demonstrate our theoretical analysis'.

### 4.2.1

> Due to f(n) = Θ(nlg1), so we get...

'Due to' and 'so' shouldn't be used together in one sentence.

### 4.3.1

> Each squaring results **in** approximately double the number of digits of the previous, and so, if multiplication of two d digit numbers is implemented in O(dk) operations for some fxed k then the complexity of computing xn is given by:

The 'results in' should be followed by a noun. 

I think this part (4.3.1) is difficult to understand. Maybe we can discuss and rewrite it.

**Comment by zurl** [comment]
@Crossady

**Comment by zurl** [comment]
@tanquer 1.1.3 is not incorrect。

**Comment by Crossady** [comment]
well, I find the 4.3.1 in wikipedia. And that is about [Computational complexity](https://en.wikipedia.org/wiki/Computational_complexity_theory)(计算复杂度）, which is a little different from time complexity. So I think it can be removed and later I will add some words.
